export const fallbackData = {
  settings: {
    restaurantName: 'Primitivo Grill',
    tagline: 'Wagyu & Dry-Aged Steakhouse — St. Julian\'s, Malta',
    heroSubtitle: 'Bold flavours, rugged vibes, refined taste.',
    reservationUrl: 'https://eatapp.co/reserve/primitivo-grill-33-triq-paceville-33-saint-julian-s-island-of-malta-stj1012-malta',
    aboutLabel: 'Our Story',
    aboutTitle: 'Where Fire\nMeets Craft',
    aboutText1: 'Primitivo is not just a steakhouse — it\'s an *experience carved in flame*. In the heart of St. Julian\'s, we honour the primal art of fire-cooked cuisine. Premium Japanese Wagyu, hand-selected dry-aged cuts, and an open kitchen where every sear, every flame, every plate tells a story.',
    aboutText2: 'Our philosophy is simple: *bold flavours, zero pretension*. Every dish is crafted with obsessive attention, from the first char to the final garnish. This is meat, elevated.',
    aboutQuote: 'The best steak I have ever had in my life. The Wagyu melted on my tongue. This place is pure magic.',
    aboutQuoteCite: 'Google Review, 5 Stars',
    dividerQuote: 'Every cut has a story.',
    dividerHighlight: 'We let the fire tell it.',
    googleRating: '4.7',
    googleReviews: '424',
    tripadvisorRating: '4.8',
    tripadvisorReviews: '447',
    hours: 'Mon – Sat: 18:30 – 23:30\nSunday: 12:30 – 14:30 &\n18:30 – 23:30',
    address: '33, Triq Paceville\nSt. Julian\'s STJ1012\nMalta',
    phone: '+356 0000 0000',
    instagramUrl: 'https://instagram.com/primitivomalta',
    instagramHandle: '@primitivomalta',
    facebookUrl: 'https://facebook.com/primitivogrillmalta',
    googleMapsEmbed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d810.6!2d14.4908!3d35.9225!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x130e452d3081f40b%3A0x9d7e29b6f0a3c2b8!2sPrimitivo%20Grill!5e0!3m2!1sen!2smt!4v1',
    reserveTitle: 'Your Table\nAwaits',
    reserveText: 'Every evening at Primitivo is crafted, never rushed. Reserve your place and let us take care of the rest.',
  },
  categories: [
    {
      _id: 'cat-1',
      title: 'Starters',
      order: 1,
      items: [
        { name: 'Beef Tartare', description: 'Hand-cut prime beef, egg yolk, capers, shallot, house dressing', tag: 'Signature' },
        { name: 'Wild Boar Meatballs', description: 'Slow-braised wild boar, caramelised onion, rustic sauce' },
        { name: 'Fried Calamari', description: 'Crispy rings, lemon zest, garlic aioli' },
      ],
    },
    {
      _id: 'cat-2',
      title: 'Mains — The Grill',
      order: 2,
      items: [
        { name: 'Japanese Wagyu', description: 'A5 grade, exquisite marbling, served with seasonal accompaniments', tag: 'Premium' },
        { name: 'Dry-Aged Ribeye', description: '28-day aged, intense depth of flavour, bone-in option available' },
        { name: 'T-Bone', description: 'The classic, two steaks in one — fillet and sirloin on the bone' },
        { name: 'Prime Fillet', description: 'The tenderest cut, centre-cut, char-grilled to your preference' },
        { name: 'Dry Spanish Cut', description: 'Iberian heritage, dry-aged with Mediterranean character' },
        { name: 'Guancialini di Maiale', description: 'Braised pork cheeks, falling apart tender, rich glaze' },
      ],
    },
    {
      _id: 'cat-3',
      title: 'Desserts',
      order: 3,
      items: [
        { name: 'Tiramisu — Live', description: 'Prepared tableside by our team, a theatrical finish to your evening', tag: 'Signature Experience' },
        { name: 'Parfait', description: 'Seasonal flavours, layered textures, delicate presentation' },
        { name: 'Panna Cotta', description: 'Silky vanilla custard, fruit coulis, fresh berries' },
      ],
    },
    {
      _id: 'cat-4',
      title: 'Wine & Drinks',
      order: 4,
      items: [
        { name: 'Curated Wine Selection', description: 'Italian, French, and New World bottles, hand-picked to complement our grill' },
        { name: 'Cordials & Digestifs', description: 'A refined close — grappa, amaro, limoncello, and more' },
      ],
    },
  ],
  cards: [
    {
      _id: 'exp-1',
      title: 'Open Kitchen',
      description: 'Watch your steak being crafted through our floor-to-ceiling glass kitchen. Every sear, every flame — theatre you can taste.',
      iconSvg: '<path d="M24 4c-2 8-10 14-10 24a10 10 0 0020 0C34 18 26 12 24 4z"/><path d="M24 38v-8M20 34h8"/>',
      order: 1,
    },
    {
      _id: 'exp-2',
      title: 'Live Tiramisu',
      description: 'Our signature finale. Prepared fresh at your table with flair — layers of mascarpone, espresso, and pure theatre.',
      iconSvg: '<circle cx="24" cy="20" r="12"/><path d="M16 36h16M12 40h24M20 32h8"/>',
      order: 2,
    },
    {
      _id: 'exp-3',
      title: 'The Team',
      description: 'Liz, Niko, Daniel and our crew don\'t just serve — they create your evening. Warm, knowledgeable, and unforgettable.',
      iconSvg: '<path d="M8 40l8-16 8 10 8-20 8 26"/><circle cx="12" cy="12" r="4"/>',
      order: 3,
    },
  ],
  gallery: [
    { _id: 'gal-1', label: 'The Open Kitchen', order: 1 },
    { _id: 'gal-2', label: 'Wagyu Selection', order: 2 },
    { _id: 'gal-3', label: 'Live Tiramisu', order: 3 },
    { _id: 'gal-4', label: 'Dry-Aged Cuts', order: 4 },
    { _id: 'gal-5', label: 'The Atmosphere', order: 5 },
  ],
  reviews: [
    {
      _id: 'rev-1',
      text: 'Absolutely phenomenal experience. The Wagyu was cooked to perfection and the live Tiramisu was the highlight of our trip to Malta. Liz was an incredible host — made us feel like family.',
      author: 'Sarah M.',
      source: 'TripAdvisor',
      stars: 5,
    },
    {
      _id: 'rev-2',
      text: 'Without a doubt, the best steakhouse in Malta. Dry-aged ribeye was mind-blowing. Niko recommended the perfect wine pairing. The open kitchen concept adds so much to the atmosphere. Already booked our return.',
      author: 'Marco R.',
      source: 'Google',
      stars: 5,
    },
    {
      _id: 'rev-3',
      text: 'We came for the steak, stayed for the experience. Daniel\'s service was impeccable — attentive without being intrusive. The beef tartare starter and the T-bone were both exceptional. The ambiance is dark, intimate, and incredibly cool.',
      author: 'James & Elena',
      source: 'TripAdvisor',
      stars: 5,
    },
    {
      _id: 'rev-4',
      text: 'A hidden gem in Paceville. Forget the clubs — THIS is where you want to spend your evening. The wild boar meatballs were divine and the Wagyu… no words. Just go.',
      author: 'Claudia F.',
      source: 'Google',
      stars: 5,
    },
  ],
}
